<div id="rees46_auth_block" style="display: none;">
	<div class="admin__control-table-wrapper">
		<table class="admin__control-table">
			<tr>
				<td style="text-align: center;">
					<button type="button" class="action-secondary" id="rees46_login_button"><span><?php echo __('Authorize'); ?></span></button>
				</td>
				<td style="text-align: center;">
					<button type="button" class="action-secondary" id="rees46_register_button"><span><?php echo __('Register'); ?></span></button>
				</td>
			</tr>
		</table>
	</div>
</div>
