<!--
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
-->
<!-- BEGIN REES46 INIT -->
<script type="text/javascript">
(function(r){window.r46=window.r46||function(){(r46.q=r46.q||[]).push(arguments)};var s=document.getElementsByTagName(r)[0],rs=document.createElement(r);rs.async=1;rs.src='//cdn.rees46.com/v3.js';s.parentNode.insertBefore(rs,s);})('script');
<?php echo $block->getTrackingCode(); ?>
</script>
<!-- END REES46 INIT -->
