<?php
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
	<div class="rees46 rees46-recommend">
		<div class="recommender-block-title"><?php echo $block->getTitle() ? __($block->getTitle()) : ''; ?></div>
		<div class="recommended-items">
			<?php foreach ($block->getProductCollection()->getItems() as $_item): ?>
			<div class="recommended-item">
				<div class="recommended-item-photo">
					<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><?php echo $block->getImage($_item, 'new_products_content_widget_grid')->toHtml(); ?></a>
				</div>
				<div class="recommended-item-title">
					<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><?php echo $block->escapeHtml($_item->getName()) ?></a>
				</div>
				<div class="recommended-item-price">
					<?php echo $block->getProductPriceHtml($_item, 'widget-product-grid'); ?>
				</div>
				<div class="recommended-item-action">
					<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><?php echo $text_more = 'More'; ?></a>
				</div>
			</div>
			<?php endforeach ?>
		</div>
	</div>
<?php endif;?>
