<?php
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
?>
<div id="rees46_help_block">
	<style>
		#rees46_auth_block {
			display: block !important;
		}
		#rees46_auth_block + .section-config,
		#rees46_auth_block + div + .section-config,
		#config-edit-form .section-config {
			display: none;
		}
	</style>
	<script type="text/javascript">
	    var rees46AjaxUrl = '<?php echo $this->getUrl('rees46/ajax/ajax') ?>';

	    require(['jquery'], function($){
	        $(document).ready(function() {
	            rees46Init();
	        });
	    });
	</script>
	<div class="message message-info info">
		<p><?php echo __('Go to your REES46 store dashboard to get the access to:'); ?></p>
		<ul style="padding-left: 40px;">
			<li><?php echo __('Triggered emails'); ?></li>
			<li><?php echo __('Email marketing tool'); ?></li>
			<li><?php echo __('Personalized search'); ?></li>
			<li><?php echo __('Web push triggered notifications'); ?></li>
			<li><?php echo __('Instant web push notifications'); ?></li>
			<li><?php echo __('Audience segmentation'); ?></li>
			<li><?php echo __('Abandoned cart remarketing tool'); ?></li>
		</ul>
		<button onclick="window.open('https://rees46.com/customers/sign_in', '_blank'); return false;" class="primary"><?php echo __('REES46 dashboard'); ?></button><br><br>
		<p><?php echo __('Documentation:'); ?> <a href="<?php echo __('http://docs.rees46.com/display/en/Magento+2+Module'); ?>" target="_blank"><?php echo __('http://docs.rees46.com/display/en/Magento+2+Module'); ?></a></p>
	</div>
</div>
