<!--
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
-->
<div id="rees46_help_block">
	<style>
		#rees46_auth_block + .section-config,
		#rees46_auth_block + div + .section-config {
			display: none;
		}
	</style>
	<script type="text/javascript">
	    var rees46AjaxUrl = '<?php echo $this->getUrl('rees46/ajax/ajax') ?>';

	    require(['jquery'], function($){
	        $(document).ready(function() {
	            rees46Init();
	        });
	    });
	</script>
	<div class="message message-info info">
		<p>Go to your REES46 store dashboard to get the access to:</p>
		<ul style="padding-left: 40px;">
			<li>Triggered emails</li>
			<li>Email marketing tool</li>
			<li>Personalized search</li>
			<li>Web push triggered notifications</li>
			<li>Instant web push notifications</li>
			<li>Audience segmentation</li>
			<li>Abandoned cart remarketing tool</li>
		</ul>
		<button onclick="window.open('https://rees46.com/customers/sign_in', '_blank'); return false;" class="primary">REES46 dashboard</button><br><br>
		<p>Documentation: <a href="http://docs.rees46.com/display/en/PrestaShop+Module" target="_blank">http://docs.rees46.com/display/en/PrestaShop+Module</a></p><br>
		<p>Support: <a href="https://addons.prestashop.com/en/contact-us?id_product=18056" target="_blank">https://addons.prestashop.com/en/contact-us?id_product=18056</a></p>
	</div>
</div>
